import { AudioContext } from "node-web-audio-api";
import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DEFAULT_CUTOFF_HZ, DEFAULT_TREMOLO_HZ } from "./pencil-mapper.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ASSETS = path.join(__dirname, "..", "assets");

/**
 * Epic 9: three mood stems, each a distinct pre-rendered WAV.
 * All are at the same native 96 BPM tempo so bpmToPlaybackRate()
 * continues to work correctly on top of whichever stem is active.
 * Generated by: npm run prepare-stems (EQ variants from bed.wav)
 *   or npm run generate-stems (distinct fal.ai compositions, needs FAL_KEY)
 */
const STEM_PATHS = {
  calm:      path.join(ASSETS, "stem-calm.wav"),
  energetic: path.join(ASSETS, "stem-energetic.wav"),
  tense:     path.join(ASSETS, "stem-tense.wav"),
};

// Tremolo (Epic 6) is a periodic gain modulation: an LFO oscillator feeds a
// depth-scaling gain node into the output gain's AudioParam, which Web Audio
// sums with the param's base value. Base/depth are fixed structural
// constants (not part of the pencil->param mapping), so they live here
// rather than in pencil-mapper.js.
const TREMOLO_BASE_GAIN = 0.85;
const TREMOLO_DEPTH = 0.15; // gain oscillates in [BASE-DEPTH, BASE+DEPTH] = [0.7, 1.0]

/** Crossfade duration in seconds (Epic 9). */
export const CROSSFADE_DURATION_SEC = 3;

/**
 * Loads all three mood stems and loops them simultaneously. Each stem feeds
 * through its own GainNode into a shared filter / panner / tremolo chain.
 * The currently active mood stem has gain=1; the others are silent (gain=0).
 * Crossfading between moods ramps the gains simultaneously.
 *
 * Returns setPlaybackRate() and crossfadeTo() instead of a bare sourceNode,
 * since Epic 9 owns multiple source nodes that must all be kept in sync.
 *
 * Audio graph (per stem):
 *   stemSource[mood] → stemGain[mood] ─┬───────────────────────────────────────┬→ filterNode → …
 *                              (calm, energetic, tense all feed the same chain)
 *
 * The shared filter chain from Epic 6 is unchanged:
 *   filterNode (lowpass/brightness) → pannerNode (stereo) → tremoloGain → destination
 */
export async function startPlayback() {
  // Verify stems exist (fail fast with a clear error rather than a cryptic crash).
  for (const [mood, p] of Object.entries(STEM_PATHS)) {
    if (!existsSync(p)) {
      throw new Error(
        `[playback] missing stem: ${p}\n` +
        `Run "npm run prepare-stems" to generate stems from bed.wav, ` +
        `or "npm run generate-stems" (requires FAL_KEY) for distinct fal.ai compositions.`
      );
    }
  }

  const context = new AudioContext();

  // ── Load and decode all three stems ────────────────────────────────────────
  const stemSources = {};
  const stemGains   = {};

  for (const [mood, stemPath] of Object.entries(STEM_PATHS)) {
    const raw = await readFile(stemPath);
    const ab  = raw.buffer.slice(raw.byteOffset, raw.byteOffset + raw.byteLength);
    const buf = await context.decodeAudioData(ab);

    const source = context.createBufferSource();
    source.buffer = buf;
    source.loop   = true;
    source.playbackRate.value = 1.0;

    const gainNode = context.createGain();
    // Start with ENERGETIC audible, others silent.
    gainNode.gain.value = mood === "energetic" ? 1.0 : 0.0;

    stemSources[mood] = source;
    stemGains[mood]   = gainNode;

    console.log(`[playback] loaded ${mood}: ${stemPath} (${buf.duration.toFixed(1)}s)`);
  }

  // ── Epic 6 shared melody/timbre chain ──────────────────────────────────────
  const filterNode = context.createBiquadFilter();
  filterNode.type = "lowpass";
  filterNode.frequency.value = DEFAULT_CUTOFF_HZ;

  const pannerNode = context.createStereoPanner();

  const tremoloGain = context.createGain();
  tremoloGain.gain.value = TREMOLO_BASE_GAIN;

  const lfo = context.createOscillator();
  lfo.type = "sine";
  lfo.frequency.value = DEFAULT_TREMOLO_HZ;
  const lfoDepth = context.createGain();
  lfoDepth.gain.value = TREMOLO_DEPTH;
  lfo.connect(lfoDepth);
  lfoDepth.connect(tremoloGain.gain);

  // Connect each stem through its gain into the shared filter chain.
  for (const mood of Object.keys(STEM_PATHS)) {
    stemSources[mood].connect(stemGains[mood]);
    stemGains[mood].connect(filterNode);
  }
  filterNode.connect(pannerNode);
  pannerNode.connect(tremoloGain);
  tremoloGain.connect(context.destination);

  // Start all stems simultaneously so they stay in phase when crossfading.
  lfo.start();
  for (const source of Object.values(stemSources)) source.start();

  console.log("[playback] all stems running. starting with energetic mood.");

  // ── Crossfade state ─────────────────────────────────────────────────────────
  let _activeMood = "energetic";

  // ── Exported controls ───────────────────────────────────────────────────────

  /**
   * Set playbackRate on all stem source nodes simultaneously.
   * Replaces the old `sourceNode.playbackRate.value = rate` pattern.
   *
   * @param {number} rate
   */
  function setPlaybackRate(rate) {
    for (const source of Object.values(stemSources)) {
      source.playbackRate.value = rate;
    }
  }

  /**
   * Crossfade to a target mood stem over `durationSec` seconds.
   * All other stems ramp to 0; the target ramps to 1.
   * Safe to call during an ongoing crossfade — ramps are cancelled and
   * restarted from the current gain values, avoiding clicks.
   *
   * @param {"calm"|"energetic"|"tense"} targetMood
   * @param {number} [durationSec=CROSSFADE_DURATION_SEC]
   */
  function crossfadeTo(targetMood, durationSec = CROSSFADE_DURATION_SEC) {
    if (targetMood === _activeMood) return;
    _activeMood = targetMood;
    const now = context.currentTime;
    const end = now + durationSec;
    for (const [mood, gainNode] of Object.entries(stemGains)) {
      const current = gainNode.gain.value;
      gainNode.gain.cancelScheduledValues(now);
      gainNode.gain.setValueAtTime(current, now);
      gainNode.gain.linearRampToValueAtTime(mood === targetMood ? 1.0 : 0.0, end);
    }
    console.log(`[playback] crossfade: ${_activeMood === targetMood ? _activeMood : _activeMood} → ${targetMood} (${durationSec}s)`);
  }

  /** @returns {"calm"|"energetic"|"tense"} */
  function getActiveMood() { return _activeMood; }

  return {
    context,
    filterNode,
    pannerNode,
    tremoloGain,
    lfo,
    setPlaybackRate,
    crossfadeTo,
    getActiveMood,
  };
}
